name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@ff22772bd67b63334ef449bdb936a326c4cd31af
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR1Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
