name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@5f2be55e027445c01c254b94a4043b0056ec9095
    permissions:
      contents: write
    with:
      modules: >-
        ["UplayR1Unlocker"]

      zip_command: >
        zip -j $ZIP_NAME
        artifacts/*/*.dll
